import type {
  Band,
  EventLead,
  Proposal,
  Musician,
  EventBooking,
  FollowUpAutomation,
  Contract,
  Payment,
} from "@/types/entities";

const today = new Date();
const addDays = (d: Date, days: number) => {
  const x = new Date(d);
  x.setDate(x.getDate() + days);
  return x.toISOString();
};

export const seedBand: Band = {
  id: "band-1",
  name: "Banda Teste",
  description: "Banda de pop/rock para casamentos, eventos corporativos e festas particulares.",
  genres: ["Pop", "Rock", "MPB", "Sertanejo"],
  city: "São Paulo, SP",
  contactPhone: "(11) 99999-9999",
  socialLinks: {
    instagram: "@bandateste",
    spotify: "bandateste",
  },
};

export const seedLeads: EventLead[] = [
  {
    id: "lead-1",
    name: "Camila Souza",
    phone: "(11) 98888-1111",
    email: "camila@email.com",
    eventType: "Casamento",
    guests: 180,
    city: "São Paulo, SP",
    date: addDays(today, 95),
    status: "QUALIFIED",
    heatScore: 92,
    notes: "Cerimônia ao ar livre, recepção interna. Quer banda + DJ.",
    createdAt: addDays(today, -7),
  },
  {
    id: "lead-2",
    name: "Marcos Oliveira",
    phone: "(11) 97777-2222",
    email: "marcos@empresa.com",
    eventType: "Evento Corporativo",
    guests: 300,
    city: "São Paulo, SP",
    date: addDays(today, 32),
    status: "PROPOSAL_SENT",
    heatScore: 78,
    notes: "Final de ano da empresa. Pediu repertório anos 80/90.",
    createdAt: addDays(today, -3),
  },
  {
    id: "lead-3",
    name: "Juliana Pires",
    phone: "(11) 96666-3333",
    email: "ju.pires@email.com",
    eventType: "Aniversário 30 anos",
    guests: 80,
    city: "Campinas, SP",
    date: addDays(today, 14),
    status: "NEGOTIATION",
    heatScore: 85,
    notes: "Quer cover de Beyoncé na entrada.",
    createdAt: addDays(today, -10),
  },
  {
    id: "lead-4",
    name: "Roberto Mendes",
    phone: "(11) 95555-4444",
    email: "roberto@email.com",
    eventType: "Casamento",
    guests: 120,
    city: "São Paulo, SP",
    date: addDays(today, 60),
    status: "NEW",
    heatScore: 60,
    notes: "Pediu orçamento via Instagram.",
    createdAt: addDays(today, -1),
  },
  {
    id: "lead-5",
    name: "Patrícia Lima",
    phone: "(11) 94444-5555",
    email: "patricia@email.com",
    eventType: "Festa de 15 anos",
    guests: 200,
    city: "Guarulhos, SP",
    date: addDays(today, 45),
    status: "CONTACTED",
    heatScore: 55,
    notes: "Está comparando 3 bandas.",
    createdAt: addDays(today, -5),
  },
  {
    id: "lead-6",
    name: "Felipe Costa",
    phone: "(11) 93333-6666",
    email: "felipe@email.com",
    eventType: "Casamento",
    guests: 150,
    city: "São Paulo, SP",
    date: addDays(today, -10),
    status: "WON",
    heatScore: 100,
    notes: "Contrato fechado!",
    createdAt: addDays(today, -30),
  },
];

export const seedProposals: Proposal[] = [
  {
    id: "prop-1",
    leadId: "lead-2",
    title: "Pacote Corporate Premium — 4h ao vivo",
    packageType: "PREMIUM",
    price: 12500,
    expiresAt: addDays(today, 5),
    status: "VIEWED",
    publicLink: "/p/abc123",
    createdAt: addDays(today, -2),
  },
  {
    id: "prop-2",
    leadId: "lead-3",
    title: "Aniversário Juliana — Show 2h",
    packageType: "STANDARD",
    price: 6800,
    expiresAt: addDays(today, 7),
    status: "SENT",
    publicLink: "/p/def456",
    createdAt: addDays(today, -1),
  },
  {
    id: "prop-3",
    leadId: "lead-6",
    title: "Casamento Felipe & Carol",
    packageType: "PREMIUM",
    price: 14000,
    expiresAt: addDays(today, -25),
    status: "ACCEPTED",
    acceptedAt: addDays(today, -22),
    publicLink: "/p/ghi789",
    createdAt: addDays(today, -28),
  },
];

export const seedMusicians: Musician[] = [
  {
    id: "mus-1",
    name: "Diego Santos",
    instrument: "Vocal",
    cacheValue: 1200,
    availability: "AVAILABLE",
    transportCost: 80,
    phone: "(11) 99000-1111",
  },
  {
    id: "mus-2",
    name: "Larissa Tavares",
    instrument: "Backing Vocal",
    cacheValue: 800,
    availability: "AVAILABLE",
    transportCost: 60,
    phone: "(11) 99000-2222",
  },
  {
    id: "mus-3",
    name: "André Ribeiro",
    instrument: "Guitarra",
    cacheValue: 900,
    availability: "BUSY",
    transportCost: 70,
    phone: "(11) 99000-3333",
  },
  {
    id: "mus-4",
    name: "Bruno Lopes",
    instrument: "Baixo",
    cacheValue: 850,
    availability: "AVAILABLE",
    transportCost: 70,
    phone: "(11) 99000-4444",
  },
  {
    id: "mus-5",
    name: "Renato Silva",
    instrument: "Bateria",
    cacheValue: 950,
    availability: "AVAILABLE",
    transportCost: 90,
    phone: "(11) 99000-5555",
  },
  {
    id: "mus-6",
    name: "Camila Reis",
    instrument: "Teclado",
    cacheValue: 850,
    availability: "ON_LEAVE",
    transportCost: 65,
    phone: "(11) 99000-6666",
  },
];

export const seedBookings: EventBooking[] = [
  {
    id: "book-1",
    leadId: "lead-6",
    proposalId: "prop-3",
    title: "Casamento Felipe & Carol",
    eventDate: addDays(today, -10),
    venue: "Espaço Villa Bisutti",
    duration: 4,
    setupTime: 2,
    totalCost: 6500,
    profit: 7500,
    musicianIds: ["mus-1", "mus-2", "mus-3", "mus-4", "mus-5"],
    status: "COMPLETED",
  },
  {
    id: "book-2",
    leadId: "lead-3",
    title: "Aniversário Juliana 30 anos",
    eventDate: addDays(today, 14),
    venue: "Salão Estrela, Campinas",
    duration: 3,
    setupTime: 1.5,
    totalCost: 3200,
    profit: 3600,
    musicianIds: ["mus-1", "mus-2", "mus-4", "mus-5"],
    status: "CONFIRMED",
  },
  {
    id: "book-3",
    leadId: "lead-2",
    title: "Confraternização Corporativa",
    eventDate: addDays(today, 32),
    venue: "Hotel Maksoud Plaza",
    duration: 4,
    setupTime: 2,
    totalCost: 5800,
    profit: 6700,
    musicianIds: ["mus-1", "mus-2", "mus-3", "mus-4", "mus-5", "mus-6"],
    status: "SCHEDULED",
  },
];

export const seedAutomations: FollowUpAutomation[] = [
  {
    id: "auto-1",
    name: "Boas-vindas ao novo lead",
    triggerType: "LEAD_CREATED",
    delayDays: 0,
    channel: "WHATSAPP",
    messageTemplate:
      "Olá {nome}! 👋 Recebi seu contato sobre {evento}. Em até 24h te envio uma proposta personalizada.",
    active: true,
  },
  {
    id: "auto-2",
    name: "Follow-up proposta enviada",
    triggerType: "PROPOSAL_SENT",
    delayDays: 2,
    channel: "WHATSAPP",
    messageTemplate:
      "Oi {nome}, conseguiu dar uma olhada na proposta? Qualquer dúvida estou por aqui!",
    active: true,
  },
  {
    id: "auto-3",
    name: "Alerta proposta expirando",
    triggerType: "PROPOSAL_EXPIRING",
    delayDays: 1,
    channel: "WHATSAPP",
    messageTemplate:
      "{nome}, sua proposta expira amanhã. Quer garantir a data do seu evento?",
    active: true,
  },
  {
    id: "auto-4",
    name: "Lembrete de evento (cliente)",
    triggerType: "EVENT_UPCOMING",
    delayDays: 7,
    channel: "EMAIL",
    messageTemplate: "Faltam 7 dias para o seu evento! Vamos alinhar os últimos detalhes?",
    active: false,
  },
];

export const seedContracts: Contract[] = [
  {
    id: "contract-1",
    bookingId: "book-1",
    signedAt: addDays(today, -22),
    fileUrl: "/contracts/contract-1.pdf",
    paymentStatus: "PAID",
    installmentCount: 2,
    totalValue: 14000,
    createdAt: addDays(today, -25),
  },
  {
    id: "contract-2",
    bookingId: "book-2",
    signedAt: addDays(today, -8),
    fileUrl: "/contracts/contract-2.pdf",
    paymentStatus: "PENDING",
    installmentCount: 2,
    totalValue: 6800,
    createdAt: addDays(today, -10),
  },
];

export const seedPayments: Payment[] = [
  {
    id: "pay-1",
    contractId: "contract-1",
    amount: 7000,
    method: "PIX",
    dueDate: addDays(today, -22),
    status: "PAID",
    transactionId: "TX-001",
    installmentNumber: 1,
  },
  {
    id: "pay-2",
    contractId: "contract-1",
    amount: 7000,
    method: "PIX",
    dueDate: addDays(today, -10),
    status: "PAID",
    transactionId: "TX-002",
    installmentNumber: 2,
  },
  {
    id: "pay-3",
    contractId: "contract-2",
    amount: 3400,
    method: "PIX",
    dueDate: addDays(today, -7),
    status: "PAID",
    transactionId: "TX-003",
    installmentNumber: 1,
  },
  {
    id: "pay-4",
    contractId: "contract-2",
    amount: 3400,
    method: "PIX",
    dueDate: addDays(today, 12),
    status: "PENDING",
    installmentNumber: 2,
  },
];
